import Head from "next/head";
import Image from "next/image";
import l from "@/assets/landing.png";
import e from "@/assets/event.png";
import i from "@/assets/instaa.png";
import s from "@/assets/svg.png";
import r from "@/assets/i.png";
import Layout from "@/components/layout";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import  {Articles} from "@/components/Articles";
import Footer from "@/components/Footer";
import Updates from "@/components/Updates";
import AOS from "aos";
import 'aos/dist/aos.css';
import { useEffect } from "react";



// import styles from '@/styles/Home.module.css'




type Props = {
  className?: string;
};


const inter = Inter({ subsets:["latin"] });

export default function Home() {
  useEffect(()=>{
    AOS.init({duration:2000,once:false});
  },[]
  );
  return (
    <>
      <Head>
        <title>marksoc DTU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Header/>
       <div className="flex flex-shrink-0 flex-col h-max w-max-screen justify-center">
       
        <div className="flex flex-shrink-0 flex-row h-max w-max-screen pl-20 items-center  justify-center">
          <div className="animation flex flex-shrink-0 flex-col gap-2 item-center m-10 w-1/2" data-aos="fade-left" >
            <div className="flex flex-shrink-0 text-5xl font-Inter font-bold  ">MARKETING</div>
            <div className="flex flex-shrink-0 text-5xl text-dark font-Inter font-bold ">SOCIETY DTU</div>
            <div className="flex flex-shrink-0 font-Inter  ">Join us at MarkSoc DTU! We re a group of students aiming to connect fellow students with real-world opportunities from our university.  Help us expand our community and build a network of like-minded individuals. Let s make the most of the opportunities together!</div>

          </div>
          <div className=" animation  flex flex-shrink-0  h-max w-1/2" data-aos="fade-right">
          <Image src={l} alt="logo" />
          </div>

        </div>

        <div className="flex flex-shrink-0 flex-row h-max w-max-screen items-center font-bold justify-center">
          <div className=" animation flex flex-shrink-0 flex-col h-max m-5 p-10 px-14 gap-2 items-center rounded-md  border border-dark border-4 justify-center " data-aos="flip-right">
            <div className="flex flex-shrink-0  items-center   justify-center"><Image src={e} alt="logo" /></div>
            <div className="flex flex-shrink-0  items-center   justify-center"><Updates name="26"
            /></div>
            <div className="flex flex-shrink-0  items-center   justify-center">Events</div>

          </div>

          <div className=" animation flex flex-shrink-0 flex-col h-max m-5 p-10 gap-2 items-center rounded-md border border-dark border-4 justify-center" data-aos="flip-right">
            <div className="flex flex-shrink-0  items-center   justify-center"><Image src={s} alt="logo" /></div>
            <div className="flex flex-shrink-0  items-center   justify-center"><Updates name="26"
            /></div>
            <div className="flex flex-shrink-0  items-center   justify-center">Registrations</div>

          </div>

          <div className="animation flex flex-shrink-0 flex-col h-max m-5 p-10 px-14 gap-2 items-center rounded-md border border-dark  border-4 justify-center"data-aos="flip-right">
            <div className="flex flex-shrink-0  items-center   justify-center"><Image src={s} alt="logo" /></div>
            <div className="flex flex-shrink-0  items-center   justify-center"><Updates name="26"
            /></div>
            <div className="flex flex-shrink-0  items-center   justify-center">Projects</div>

          </div>

          <div className="animation flex flex-shrink-0 flex-col h-max m-5 p-10 gap-2 items-center rounded-md  border border-dark  border-4  justify-center" data-aos="flip-right">
            <div className="flex flex-shrink-0  items-center   justify-center"><Image src={i} alt="logo" width={30} height={30} /></div>
            <div className="flex flex-shrink-0  items-center   justify-center"><Updates name="26"
            /></div>
            <div className="flex flex-shrink-0  items-center   justify-center">IG Followers</div>

          </div>



          
        </div>

       </div>



       <div className="flex flex-shrink-0 flex-col h-max w-max-screen justify-center border border-4 bg-light "><div className="flex flex-col m-10 text-5xl text-dark text-center font-bold font-Inter">LATEST ARTICLES</div><div className="flex flex-shrink-0 flex-col h-max w-max-screen justify-center"><Articles/></div></div>

       <div className="flex flex-col md:flex-row h-auto md:h-max justify-center items-center md:items-start">
        <div className="md:order-1 flex flex-shrink-0 w-full md:w-fit h-max rounded-md items-center justify-center md:ml-32">
         <Image src={r} alt="vectorArt" />
        </div>
       <div className="md:order-2 flex flex-col w-full md:w-max-screen">
       <div className=" animate mx-auto max-w-md md:max-w-lg p-6 bg-white rounded-md shadow-md mt-12 md:mt-8 mb-8 "  data-aos="flip-left">
       <div className="text-3xl font-semibold mb-4">Vision</div>
       <div className="text-base text-gray-700 leading-relaxed">
          We, as a society, want to provide a platform for aspiring students in our college to get proper guidance and a path to pursue their passion from scratch and to create a culture in college that would help building aspires to grow. With the help of our experienced and talented seniors, we aim to build a community that will elevate a learning space for our fellow students by conducting regular workshops to help them tackle any problem that they might be facing in the broad field of marketing.
       </div>
       </div>
       <div className=" animate mx-auto max-w-md md:max-w-lg p-6 bg-white rounded-md shadow-md mb-8" data-aos="flip-right">
       <div className="text-3xl font-semibold mb-4">Mission</div>
       <div className="text-base text-gray-700 leading-relaxed">
         MarkSoc DTU empowers students passionate about marketing by providing a dynamic platform for skill development and knowledge expansion. Our inclusive community welcomes all, offering essential skills for confident entry into the corporate world. Through practical skill development, ethical practices, and experiential learning, we prepare members for diverse opportunities in marketing. We collaborate with companies for hands-on projects and guide students to explore and nurture their passions for a thriving culture of growth.
       </div>
       </div>
       </div>
  
    </div>

       <Footer/>

      </main>
    </>
  );
};
