import Head from "next/head";
import Image from "next/image";
import l from "@/assets/landing.png";
import e from "@/assets/event.png";
import s from "@/assets/svg.png";
import Layout from "@/components/layout";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import  {Articles} from "@/components/Articles";
import Footer from "@/components/Footer";



// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>marksoc DTU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Header/>
       <div className="flex flex-col flex-shrink-0 gap-7 justify-center p-20 w-max-screen h-max">
        <div className="flex flex-shrink-0 border "> group image</div>
        <div className="flex flex-row pl-20  m-10 gap-10 flex-shrink-0">
            <div className="flex flex-col border h-1/6 w-1/6 flex-shrink-0  hover:shadow-xl  ">
                <div className="flex  border flex-shrink-0" ><Image src={l} alt="logo" /></div>
                <div className="flex border flex-shrink-0">designation</div>

            </div>

            <div className="flex flex-col border h-1/6 w-1/6 flex-shrink-0">
                <div className="flex  border flex-shrink-0" ><Image src={l} alt="logo" /></div>
                <div className="flex border flex-shrink-0">designation</div>

            </div>

            <div className="flex flex-col border h-1/6 w-1/6 flex-shrink-0">
                <div className="flex  border flex-shrink-0" ><Image src={l} alt="logo" /></div>
                <div className="flex border flex-shrink-0">designation</div>

            </div>

            <div className="flex flex-col border h-1/6 w-1/6 flex-shrink-0">
                <div className="flex  border flex-shrink-0" ><Image src={l} alt="logo" /></div>
                <div className="flex border flex-shrink-0">designation</div>

            </div>
         
        </div>


        

       </div>
       <Footer/>
      </main>
    </>
  );
}
